server:
  port: 80
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
#    url: jdbc:mysql://113.45.240.54/blog?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://127.0.0.1/blog?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    password: Xwt@0629Cw
    password: "0629"

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 3000
      database: 8

#==============================邮箱配置=======================================
  mail:
    host: smtp.qq.com
    port: 465
    username: 2970929802@qq.com    # 修改为您的QQ邮箱
    password: jfqaizfnrskidgbd    # 修改为您的QQ邮箱授权码
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: jakarta.net.ssl.SSLSocketFactory
          starttls:
            enable: true
            required: true

##==============================knife4j配置==============================
## knife4j配置设置
#knife4j:
#  setting:
#    # 启用Swagger Models功能
#    enableSwaggerModels: true
#    # 启用文档管理功能
#    enableDocumentManage: true
#    # 启用版本控制功能
#    enableVersion: true
#    # 设置文档语言为中文
#    language: zh-CN

#==============================公众号配置==============================
wechat:
  app-id: wx9102d631d271b410
  app-secret: beba658104a18fc76de51759129ba0e6
  domain: http://53cf52aa.r33.cpolar.top
  redirect-uri: webchat/authCallback

#==============================豆包推理AI配置=======================================
ai:
  # API Key
  apiKey:
  baseUrl: https://ark.cn-beijing.volces.com/api/v3
  # 推理接入点ID
  model:

#============================第三方登录配置信息===================================
qq:
  app-id:
  app-secret:
  redirect-url: https://www.shiyit.com/mojian/api/auth/callback/qq
weibo:
  app-id:
  app-secret:
  redirect-url: https://www.shiyit.com/mojian/api/auth/weibo

gitee:
  app-id:
  app-secret:
  redirect-url: https://www.shiyit.com/mojian/api/auth/callback/gitee

github:
  app-id:
  app-secret:
  redirect-url: https://www.shiyit.com/shiyi/mojian/api/auth/callback/github
