server:
  port: 443
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:mysql://数据库?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false&allowPublicKeyRetrieval=true
    #url: jdbc:mysql://127.0.0.1:3307/mxxl?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    #username: LDS7871
    username:

    password:

    hikari:
      # 连接最大存活时间，建议设置比数据库的 wait_timeout 小几分钟
      max-lifetime: 300000  # 5分钟
      # 连接超时时间
      connection-timeout: 30000  # 30秒
      # 最小空闲连接数
      minimum-idle: 5
      # 最大连接数
      maximum-pool-size: 15
      # 空闲连接超时时间
      idle-timeout: 300000  # 5分钟
      # 测试连接是否有效
      connection-test-query: SELECT 1

  data:
    redis:
     # host: 113.45.240.54
      host: 127.0.0.1
      port: 6379
      database: 1
      timeout: 30000
     # password: "123456"

#==============================邮箱配置=======================================
  mail:
    host: smtp.qq.com
    port: 465
    username:     # 修改为您的QQ邮箱
    password:    # 修改为您的QQ邮箱授权码
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: jakarta.net.ssl.SSLSocketFactory

##==============================knife4j配置==============================
# knife4j配置设置
knife4j:
  setting:
    # 启用Swagger Models功能
    enableSwaggerModels: true
    # 启用文档管理功能
    enableDocumentManage: true
    # 启用版本控制功能
    enableVersion: true
    # 设置文档语言为中文
    language: zh-CN

#==============================公众号配置==============================
wechat:
  app-id:
  app-secret:
  domain:
  redirect-uri: wechat/authCallback

#==============================豆包推理AI配置=======================================
ai:
  # API Key
  apiKey:
  baseUrl: https://ark.cn-beijing.volces.com/api/v3
  # 推理接入点ID
  model:

#============================第三方登录配置信息===================================
qq:
  app-id:
  app-secret:
  redirect-url:
weibo:
  app-id:
  app-secret:
  redirect-url:

gitee:
#  app-id: c8c7f63da2086*****0f70f1924a3cc3b7c3b35dc8e8
#  app-secret: da493a7bb94468e3*****8c692f118ca807867b41e6b8f3121
#  redirect-url: http://127.0.0.1:3000/login/oauth2/code/gitee
  # 在Gitee上注册后分配的id
  clientId:
  # 在Gitee上注册后分配的secret
  clientSecret:
#  # 授权类型
#  authorizationGrantType: authorization_code
  # 回调地址
  redirectUri: http://127.0.0.1:80/oauth/callback
#  redirectUri: http://113.45.240.54:9092/oauth/callback
  # 授权范围
#  scope:
#    - user_info
#    - emails
#  # 应用的名称
#  provider: gitee
github:
  app-id:
  app-secret:
  redirect-url: #
